name: PyPI publish

on:
  push:
    branches:
    - main
  release:
    types: 
    - published

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.setup.build }}/${{ matrix.setup.arch }}
    runs-on: ${{ matrix.setup.os }}-latest
    strategy:
      matrix:
        setup:
        - os:    "ubuntu"
          build: "manylinux"
          arch:  "i686"
        - os:    "ubuntu"
          build: "manylinux"
          arch:  "x86_64"
        - os:    "ubuntu"
          build: "musllinux"
          arch:  "i686"
        - os:    "ubuntu"
          build: "musllinux"
          arch:  "x86_64"
        - os:    "macos"
          build: "macosx"
          arch:  "x86_64"
        - os:    "macos"
          build: "macosx"
          arch:  "arm64"
        - os:    "windows"
          build: "win"
          arch:  "x86"
        - os:    "windows"
          build: "win"
          arch:  "AMD64"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16
      env:
        CIBW_BUILD: "*${{ matrix.setup.build }}*"
        CIBW_SKIP: "pp*"
        CIBW_ARCHS: ${{ matrix.setup.arch }}
        CIBW_TEST_REQUIRES: pytest
        CIBW_TEST_COMMAND: pytest {project}/tests

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheel-${{ matrix.setup.os }}-${{ matrix.setup.build }}-${{ matrix.setup.arch }}
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build sdist
      run: pipx run build --sdist

    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  upload_all:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
    - name: Collect package data
      uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

#    - name: Publish package
#      uses: pypa/gh-action-pypi-publish@v1.8.11
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_API_TOKEN }}
