name: PyPI publish

on:
  release:
    types: 
    - published

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.setup.os }} (${{ matrix.setup.build }})
    runs-on: ${{ matrix.setup.os }}
    strategy:
      matrix:
        setup:
        - os:    "ubuntu-latest"
          build: "manylinux"
        - os:    "ubuntu-latest"
          build: "musllinux"
        - os:    "macos-latest"
          build: "macosx"
        - os:    "windows-latest"
          build: "win"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16
      env:
        CIBW_BUILD: "*${{ matrix.setup.build }}*"
        CIBW_SKIP: "pp*"
        CIBW_TEST_REQUIRES: pytest
        CIBW_TEST_COMMAND: pytest {project}/tests

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheel-${{ matrix.setup.os }}-${{ matrix.setup.build }}
        path: dist/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build sdist
      run: pipx run build --sdist

    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  upload_all:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
    - name: Collect package data
      uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
